'use strict';

const fs     = require('fs');
const semver = require('semver');

/**
 * Build a plain npm overrides object from Phase A items only.
 * Phase A items are single-version, same-major safe upgrades — no @^major selectors.
 *
 * For packages that appear multiple times under the same name (same major, Phase B),
 * we take the highest recommended fix version — still a safe patch/minor bump.
 */
function buildPhaseAOverrides(phasedPlan) {
  const byName = {};

  for (const item of phasedPlan) {
    if (item.phase !== 'A' || !item.recommendedVersion) continue;
    const existing = byName[item.libraryName];
    if (!existing || semver.gt(item.recommendedVersion, existing)) {
      byName[item.libraryName] = item.recommendedVersion;
    }
  }

  return byName;
}

/**
 * Build overrides for Phase B items (forced/review-required, low confidence).
 * Returns a mixed overrides object that may include:
 *   - Flat entries: { "pkg": "version" }  — same-major multi-instance items
 *   - Nested entries: { "parent": { "pkg": "version" } }  — promoted multi-major conflicts
 */
function buildPhaseBOverrides(phasedPlan) {
  const result = {};

  for (const item of phasedPlan) {
    if (item.phase !== 'B') continue;
    if (item.parentUpgradePaths) continue; // handled by buildParentUpgradeMap — not an override

    if (item.nestedOverrides) {
      // Nested overrides for promoted multi-major conflicts.
      // Multiple items in the same conflict group carry the same map — merging is idempotent.
      for (const [parent, deps] of Object.entries(item.nestedOverrides)) {
        if (!result[parent]) result[parent] = {};
        Object.assign(result[parent], deps);
      }
    } else if (item.recommendedVersion) {
      // Flat override — take highest fix version across duplicate entries
      const existing = result[item.libraryName];
      if (!existing || (typeof existing === 'string' && semver.gt(item.recommendedVersion, existing))) {
        result[item.libraryName] = item.recommendedVersion;
      }
    }
  }

  return result;
}

/**
 * Apply overrides to a package.json file.
 * Merges (does not replace) any existing overrides.
 * Returns the updated package.json object.
 */
function applyOverridesToPackageJson(packageJsonPath, overrides) {
  let pkg = {};
  if (fs.existsSync(packageJsonPath)) {
    pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
  }
  pkg.overrides = { ...(pkg.overrides || {}), ...overrides };
  return pkg;
}

/**
 * Write a standalone overrides patch file for review or manual application.
 * When meta.dependencies is non-empty, a `dependencies` section is written
 * before `overrides` to show packages that should be bumped directly.
 */
function writeOverridesPatch(outputPath, overrides, meta = {}) {
  const out = {
    _comment:    meta.comment    || 'Generated by mend-autofixer. Merge into your package.json overrides.',
    _confidence: meta.confidence || '',
  };
  if (meta.dependencies && Object.keys(meta.dependencies).length > 0) {
    out.dependencies = meta.dependencies;
  }
  if (Object.keys(overrides).length > 0) {
    out.overrides = overrides;
  }
  fs.writeFileSync(outputPath, JSON.stringify(out, null, 2) + '\n');
}

// Scenario 12/13 — prefer direct dep bump over override when the package has no
// transitive consumers (only the root depends on it).

function _buildNewRange(currentRange, fixVersion) {
  // Preserve ^ or ~ prefix from the existing range — keeps the dep semantics
  // consistent with how the user originally pinned the package.
  const m = currentRange.match(/^([~^])/);
  return m ? `${m[1]}${fixVersion}` : fixVersion;
}

/**
 * Split Phase A items into:
 *   directUpgrades — package has no transitive consumers; bump it directly in
 *                    package.json dependencies/devDependencies
 *   overrideItems  — package has transitive consumers (other packages depend on
 *                    it); needs an overrides entry to force the version everywhere
 *
 * Classification uses the dep tree when available:
 *   - Any entry with parents.length > 0 → has transitive consumers → override
 *   - All entries have parents.length === 0 → root-only dep → direct bump if found
 *     in pkg.dependencies / pkg.devDependencies
 * Falls back to checking pkg.dependencies/devDependencies when depTree is absent.
 *
 * @param {object[]} phaseAItems
 * @param {object}   pkg       already-parsed package.json object (may be {})
 * @param {Map}      [depTree] from lock-parser.parseLockFile(); optional
 */
function detectDirectDeps(phaseAItems, pkg, depTree) {
  const deps    = pkg.dependencies    || {};
  const devDeps = pkg.devDependencies || {};
  const directUpgrades = [];
  const overrideItems  = [];

  for (const item of phaseAItems) {
    if (!item.recommendedVersion) { overrideItems.push(item); continue; }

    // Determine whether this package has transitive consumers.
    // lock-parser skips the root package when building parent lists, so
    // parents.length === 0 reliably means "only the root depends on this."
    let hasTransitiveConsumers;
    if (depTree) {
      const entries = depTree.get(item.libraryName) || [];
      hasTransitiveConsumers = entries.length === 0 || entries.some(e => e.parents.length > 0);
    } else {
      // No dep tree — assume transitive consumers exist unless we can confirm
      // it is a direct dep (safe fallback: everything goes to overrides).
      hasTransitiveConsumers = true;
    }

    if (!hasTransitiveConsumers) {
      // Root-only dep — bump it in place if it's a direct dep in package.json.
      if (deps[item.libraryName] !== undefined) {
        const currentRange = deps[item.libraryName];
        directUpgrades.push({ ...item, currentRange, newRange: _buildNewRange(currentRange, item.recommendedVersion), isDev: false });
        continue;
      }
      if (devDeps[item.libraryName] !== undefined) {
        const currentRange = devDeps[item.libraryName];
        directUpgrades.push({ ...item, currentRange, newRange: _buildNewRange(currentRange, item.recommendedVersion), isDev: true });
        continue;
      }
      // depTree confirmed no transitive consumers but package.json was not provided.
      // Still classify as a direct dep (for the JSON reference output) — no range known.
      if (depTree) {
        directUpgrades.push({ ...item, currentRange: null, newRange: item.recommendedVersion, isDev: false });
        continue;
      }
    }

    // Has transitive consumers, or not in direct deps → needs an override entry.
    overrideItems.push(item);
  }

  return { directUpgrades, overrideItems };
}

/**
 * Mutate pkg by bumping direct dep versions for each item in directUpgrades.
 * Returns the modified pkg object.
 */
function applyDirectUpgrades(pkg, directUpgrades) {
  for (const item of directUpgrades) {
    const field = item.isDev ? 'devDependencies' : 'dependencies';
    if (pkg[field] && pkg[field][item.libraryName] !== undefined) {
      pkg[field][item.libraryName] = item.newRange;
    }
  }
  return pkg;
}

/**
 * Build a parent upgrade map from Phase B items that have parentUpgradePaths.
 * These are MAJOR_BUMP items resolved by upgrading a root parent within its
 * existing semver range — no override needed.
 *
 * Returns: { parentName: { allowedRange, upgradeTo, fixes: libraryName, fixVersion, childRange, isDev } }
 */
function buildParentUpgradeMap(phasedPlan) {
  const result = {};

  for (const item of phasedPlan) {
    if (item.phase !== 'B' || !item.parentUpgradePaths) continue;
    for (const p of item.parentUpgradePaths) {
      result[p.parent] = {
        allowedRange: p.parentAllowedRange,
        upgradeTo:    p.parentUpgradeVersion,
        fixes:        item.libraryName,
        fixVersion:   p.childFixVersion,
        childRange:   p.childDeclaredRange,
        isDev:        p.isDev,
      };
    }
  }

  return result;
}

module.exports = {
  buildPhaseAOverrides,
  buildPhaseBOverrides,
  buildParentUpgradeMap,
  applyOverridesToPackageJson,
  writeOverridesPatch,
  detectDirectDeps,
  applyDirectUpgrades,
};
