'use strict';

// M3.1 — GitHub Actions workflow generator.
//
// Generates a reusable GitHub Actions workflow YAML that customers add to their
// repositories to run dependency analysis (and optionally apply Phase A fixes)
// as part of their CI/CD pipeline.
//
// Safety invariants:
//   - Default mode is DRY_RUN (--dry-run) — no mutations without opt-in
//   - Applies only Phase A (never auto-applies B or C)
//   - Writes to a dedicated branch (never directly to the default branch)
//   - Uploads evidence bundles as workflow artifacts
//   - Uses least-privilege token permissions (contents: read by default,
//     contents: write only when apply + open-pr are enabled)
//   - No protected-branch writes (must be enforced via branch protection rules)

/**
 * Generate a GitHub Actions workflow YAML string for dependency analysis.
 *
 * @param {object} [opts]
 * @param {string}  [opts.nodeVersion='20']       - Node.js version
 * @param {boolean} [opts.enableApply=false]      - include the apply step (still Phase A only)
 * @param {boolean} [opts.enableOpenPR=false]      - open a PR after apply (requires enableApply)
 * @param {boolean} [opts.dryRun=true]            - pass --dry-run to the apply step
 * @param {string}  [opts.workingDirectory='.']   - directory containing the project
 * @param {string}  [opts.reportPath='']          - path to the vuln report (required at runtime)
 * @param {boolean} [opts.uploadArtifacts=true]   - upload evidence + reports as artifacts
 * @param {string}  [opts.schedule='']            - cron schedule (e.g. '0 8 * * 1')
 * @param {string}  [opts.dedicatedBranch='dependency-intelligence/auto-fix'] - apply target branch
 * @returns {string} YAML content
 */
function generateWorkflow(opts = {}) {
  const {
    nodeVersion        = '20',
    enableApply        = false,
    enableOpenPR       = false,
    dryRun             = true,
    workingDirectory   = '.',
    reportPath         = '',
    uploadArtifacts    = true,
    schedule           = '',
    dedicatedBranch    = 'dependency-intelligence/auto-fix',
  } = opts;

  // Permissions: read by default; write only when applying + opening a PR
  const needsWrite   = enableApply && enableOpenPR;
  const permissions  = needsWrite
    ? 'contents: write\n    pull-requests: write'
    : 'contents: read';

  const triggerLines = _buildTrigger(schedule);
  const applyBlock   = enableApply ? _buildApplyBlock(dryRun, dedicatedBranch) : '';
  const prBlock      = (enableApply && enableOpenPR) ? _buildPRBlock() : '';
  const artifactBlock = uploadArtifacts ? _buildArtifactBlock() : '';

  return `# Dependency Intelligence — auto-generated by mend-autofixer
# Safety: default is dry-run; apply only Phase A; dedicated branch only; evidence uploaded
# Customize: set VULN_REPORT_PATH to your scanner output
name: Dependency Intelligence

on:
${triggerLines}

permissions:
  ${permissions}

env:
  NODE_VERSION: '${nodeVersion}'
  VULN_REPORT_PATH: '${reportPath || 'path/to/your-vuln-report.json'}'
  OUT_DIR: './dep-intelligence-output'

jobs:
  analyze:
    name: Analyze dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: npm

      - name: Install mend-autofixer
        working-directory: ${workingDirectory}
        run: npm ci

      - name: Run dependency analysis (dry-run)
        working-directory: ${workingDirectory}
        run: |
          node mendfix.js analyze \\
            --report "\${{ env.VULN_REPORT_PATH }}" \\
            --out-dir "\${{ env.OUT_DIR }}"
        env:
          # Credentials: use environment variables, never CLI flags
          # MEND_TOKEN:    \${{ secrets.MEND_TOKEN }}
          # SNYK_TOKEN:    \${{ secrets.SNYK_TOKEN }}
          NODE_ENV: production
${applyBlock}${prBlock}${artifactBlock}`;
}

// ─── Azure DevOps workflow generator ─────────────────────────────────────────

/**
 * Generate an Azure DevOps pipeline YAML for dependency analysis.
 *
 * @param {object} [opts]
 * @param {string}  [opts.nodeVersion='20.x']
 * @param {boolean} [opts.enableApply=false]
 * @param {boolean} [opts.dryRun=true]
 * @param {string}  [opts.workingDirectory='.']
 * @param {string}  [opts.reportPath='']
 * @returns {string} YAML content
 */
function generateAzureDevOpsPipeline(opts = {}) {
  const {
    nodeVersion      = '20.x',
    enableApply      = false,
    dryRun           = true,
    workingDirectory = '.',
    reportPath       = '',
  } = opts;

  const applyBlock = enableApply ? `
  - task: Bash@3
    displayName: 'Apply Phase A fixes (dry-run: ${dryRun})'
    inputs:
      targetType: inline
      workingDirectory: '${workingDirectory}'
      script: |
        node mendfix.js apply \\
          --report "$(VULN_REPORT_PATH)"${dryRun ? ' \\\n          --dry-run' : ''} \\
          --out-dir "$(OUT_DIR)"
` : '';

  return `# Dependency Intelligence — auto-generated by mend-autofixer
# Safety: default is dry-run; apply only Phase A; evidence uploaded
trigger:
  - main

variables:
  NODE_VERSION: '${nodeVersion}'
  VULN_REPORT_PATH: '${reportPath || 'path/to/your-vuln-report.json'}'
  OUT_DIR: '$(Build.ArtifactStagingDirectory)/dep-intelligence'

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    displayName: 'Set up Node.js $(NODE_VERSION)'
    inputs:
      versionSpec: '$(NODE_VERSION)'

  - task: Bash@3
    displayName: 'Install mend-autofixer'
    inputs:
      targetType: inline
      workingDirectory: '${workingDirectory}'
      script: npm ci

  - task: Bash@3
    displayName: 'Run dependency analysis'
    inputs:
      targetType: inline
      workingDirectory: '${workingDirectory}'
      script: |
        node mendfix.js analyze \\
          --report "$(VULN_REPORT_PATH)" \\
          --out-dir "$(OUT_DIR)"
    env:
      NODE_ENV: production
${applyBlock}
  - task: PublishBuildArtifacts@1
    displayName: 'Upload evidence artifacts'
    inputs:
      PathtoPublish: '$(OUT_DIR)'
      ArtifactName: 'dependency-intelligence-evidence'
      publishLocation: Container
`;
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

function _buildTrigger(schedule) {
  const lines = ['  workflow_dispatch: {}'];
  if (schedule) {
    lines.push('  schedule:');
    lines.push(`    - cron: '${schedule}'`);
  } else {
    lines.push('  push:');
    lines.push('    branches: [main]');
  }
  return lines.join('\n');
}

function _buildApplyBlock(dryRun, dedicatedBranch) {
  const dryRunFlag = dryRun ? '\n            --dry-run \\' : '';
  return `
      - name: Apply Phase A fixes${dryRun ? ' (dry-run)' : ''}
        working-directory: ${'{'.repeat(1)}{ github.workspace }}
        run: |
          # Create or reset dedicated branch — never writes to default branch
          git checkout -B '${dedicatedBranch}'
          node mendfix.js apply \\
            --report "\${{ env.VULN_REPORT_PATH }}"${dryRunFlag}
            --out-dir "\${{ env.OUT_DIR }}"
        env:
          NODE_ENV: production
`;
}

function _buildPRBlock() {
  return `
      - name: Open PR for Phase A fixes
        if: success()
        run: |
          node mendfix.js apply \\
            --open-pr \\
            --platform github \\
            --report "\${{ env.VULN_REPORT_PATH }}"
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
`;
}

function _buildArtifactBlock() {
  return `
      - name: Upload evidence artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-intelligence-evidence
          path: \${{ env.OUT_DIR }}
          retention-days: 90
`;
}

module.exports = { generateWorkflow, generateAzureDevOpsPipeline };
